# Generated by Django 5.1.3 on 2024-12-13 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('file_path', models.CharField(max_length=512)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.BigIntegerField()),
                ('md5_hash', models.CharField(max_length=32)),
                ('processing_status', models.CharField(max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('mediafile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='training_data.mediafile')),
                ('duration', models.FloatField()),
                ('resolution', models.CharField(max_length=20)),
                ('fps', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
            bases=('training_data.mediafile',),
        ),
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('text', models.TextField()),
                ('language', models.CharField(max_length=10)),
                ('speaker_id', models.CharField(blank=True, max_length=100)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captions', to='training_data.videofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AudioSegment',
            fields=[
                ('mediafile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='training_data.mediafile')),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('sampling_rate', models.IntegerField()),
                ('transcription', models.TextField(blank=True)),
                ('speaker_id', models.CharField(blank=True, max_length=100)),
                ('source_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_segments', to='training_data.videofile')),
            ],
            options={
                'abstract': False,
            },
            bases=('training_data.mediafile',),
        ),
    ]
