# Generated by Django 5.1.5 on 2025-01-27 15:07

import apps.training_data.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='file_path',
        ),
        migrations.AddField(
            model_name='caption',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.training_data.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='caption',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captions_media', to='training_data.mediafile'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='S3URL',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.training_data.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='caption',
            name='end_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caption',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French')], max_length=10),
        ),
        migrations.AlterField(
            model_name='caption',
            name='start_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caption',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caption',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captions', to='training_data.videofile'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file_size',
            field=models.BigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file_type',
            field=models.CharField(blank=True, choices=[('video', 'Video'), ('audio', 'Audio'), ('subtitle', 'Subtitle'), ('csv', 'CSV'), ('ass', 'CSV')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='md5_hash',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='fps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videofile',
            name='resolution',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
